services:
  django-app:
    image: django_docker:latest

    ports:
      - "8000:8000"
    networks:
      - network_public
    labels:
      - traefik.enable=1
      - traefik.http.routers.django.rule=Host(`django.cardapiodeliveryonline.com.br`)
      - traefik.http.routers.django.entrypoints=websecure
      - traefik.http.routers.django.certresolver=letsencryptresolver
      - traefik.http.services.django.loadbalancer.server.port=8000

networks:
  network_public:
    external: true
